name: Labeler

on:
  pull_request_review:
    types: [submitted]

jobs:
  delete_awaiting_CR:
    if: contains(github.event.pull_request.labels.*.name, 'awaiting CR')
    runs-on: ubuntu-latest
    steps:
      - name: Remove awaiting CR
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: awaiting CR
      - name: Add Awaiting Second CR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: awaiting second CR

  delete_awaiting_second_CR:
    if: contains(github.event.pull_request.labels.*.name, 'awaiting second CR')
    runs-on: ubuntu-latest
    steps:
      - name: Remove ready for merge
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: awaiting second CR
      - name: Add ready for merge
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ready for merge
